site_name: C SivaSubramaniyam - Resume
site_description: C SivaSubramaniyam's professional resume website.
site_author: C SivaSubramaniyam

# Copyright
copyright: Copyright Byteshiva 2025


# Configuration
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: light blue
  font:
    text: Inter
    code: Roboto Mono
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow

  icon:
    logo: material/file-document-edit
    # logo: assets/logo.png

# Navigation
nav:
  - Home: index.md
  - About Me: about.md
  - Experience: experience.md
  - Education: education.md
  - Skills: skills.md
  - Projects: projects.md
  - Contact: contact.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/byteshiva
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/buzzshiva
    - icon: fontawesome/solid/envelope
      link: mailto:byteshiva@gmail.com
    - icon: fontawesome/brands/medium
      link: https://byteshiva.medium.com
    - icon: fontawesome/brands/twitter
      link: https://x.com/byteshiva

repo_url: https://github.com:byteshiva/resumesiva.git
repo_name: resumesiva
edit_uri: "https://github.com:byteshiva/resumesiva"
