[build]
publish = "site" # The directory where mkdocs builds the site
command = "pip install -r requirements.txt && mkdocs build" # The command to build the site

[context.deploy-preview]
command = "pip install -r requirements.txt && mkdocs build --verbose"

[context.branch-deploy]
command = "pip install -r requirements.txt && mkdocs build --verbose"

# Preview-specific settings
[build.environment]
MKDOCS_BUILD_TYPE = "preview"

# Headers for preview builds
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"